development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:6f8b01f3bf6776a47613dbeca2ab159b@barb.redistogo.com:10154/
  channel_prefix: commission_marketplace_production
